# Site settings
title: Jammy
email: noadresse@youfool.com
description: >
  Dedicated site for Jammy plugin which is a set of Eclipse plugin which
  integrates Google code jam contest services.
baseurl: "" # Before commit switch to /review.classdesign.jammy
url: "" # TODO : Update url.
twitter_username: Faylixe
github_username:  Faylixe

# Build settings
markdown: kramdown
