# Site settings
title: Jammy
email: noadresse@youfool.com
description: >
  Please note that this plugin is not provided by Google. Any responsability
  is declined if a bug occurs when you are using it in a real contest condition.
baseurl: "" # Before commit switch to /review.classdesign.jammy
url: "" # TODO : Update url.
twitter_username: Faylixe
github_username:  Faylixe

# Build settings
markdown: kramdown
