package review.classdesign.jammy.service.internal;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.security.GeneralSecurityException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.function.Consumer;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.Status;
import org.eclipse.core.runtime.jobs.IJobFunction;
import org.eclipse.core.runtime.jobs.Job;

import com.google.api.client.auth.oauth2.AuthorizationCodeFlow;
import com.google.api.client.auth.oauth2.AuthorizationCodeFlow.Builder;
import com.google.api.client.auth.oauth2.AuthorizationCodeRequestUrl;
import com.google.api.client.auth.oauth2.AuthorizationCodeTokenRequest;
import com.google.api.client.auth.oauth2.Credential;
import com.google.api.client.auth.oauth2.TokenResponse;
import com.google.api.client.extensions.jetty.auth.oauth2.LocalServerReceiver;
import com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow;
import com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.JsonFactory;
import com.google.api.client.json.jackson2.JacksonFactory;

import review.classdesign.jammy.common.EclipseUtils;
import review.classdesign.jammy.service.IGoogleLogger;

/**
 * 
 * @author fv
 */
public final class GoogleLogger implements IGoogleLogger {

	/** Default path of the JSON secret file. **/
	private static final String SECRET_PATH = "/client_secret.json";

	/** Default factory used to parse JSON data. **/
	private static final JsonFactory JSON_FACTORY = JacksonFactory.getDefaultInstance();

	/** Scopes of the created session. **/
	private static final Collection<String> SCOPES = Collections.singleton("https://www.googleapis.com/auth/plus.me");

	/** Error message displayed when an error occurs while stoping server. **/
	private static final String SERVER_STOP_ERROR_MESSAGE = "An unexpected error occurs while stopping server.";

	/** Error message displayed when an error occurs while server is waiting. **/
	private static final String SERVER_WAIT_ERROR_MESSGAGE = "An unexpected error occurs while waiting for authorization code.";

	/** Error message displayed when an error occurs during OAuth login. **/
	private static final String AUTHORIZATION_ERROR_MESSAGE = "An unexpected error occurs during OAuth login.";

	/** {@link AuthorizationCodeFlow} instance used for managing OAuth login. **/
	private final AuthorizationCodeFlow flow;

	/** Jetty server uses for token response handling. **/
	private final LocalServerReceiver receiver;

	/** Session consumer used when session is created. **/
	private final Consumer<Session> sessionConsumer;
	
	/** Listeners that are triggered when authorization is completed. **/
	private final Collection<Runnable> listeners;

	/** Redirection URI generated by the code flow. **/
	private String redirectUri;

	/**
	 * Default constructor. Uses <tt>builder</tt> to create the flow,
	 * and initializes the internal server instance used as a receiver.
	 * 
	 * @param builder Flow builder used to create flow instance.
	 * @param sessionConsumer Session consumer used when session is created.
	 */
	private GoogleLogger(final Builder builder, final Consumer<Session> sessionConsumer) {
		this.flow = builder.build();
		this.receiver = new LocalServerReceiver();
		this.listeners = new ArrayList<>(1);
		this.sessionConsumer = sessionConsumer;
	}

	/** {@inheritDoc} **/
	@Override
	public void addListener(final Runnable listener) {
		listeners.add(listener);
	}

	/** {@inheritDoc} **/
	@Override
	public void cancel() {
		try {
			receiver.stop();
		}
		catch (final IOException e) {
			EclipseUtils.showError(SERVER_STOP_ERROR_MESSAGE, e);
		}
	}

	/**
	 * Finalizes OAuth login by executing token
	 * request using the given <tt>code</tt>.
	 *
	 * @param code Code to use for retrieving the authorization token.
	 */
	private void authorize(final String code) {
		try {
			final AuthorizationCodeTokenRequest request = flow.newTokenRequest(code);
			request.setRedirectUri(redirectUri);
			final TokenResponse response = request.execute();
			final Credential credential = flow.createAndStoreCredential(response, EclipseUtils.getCurrentUser());
			sessionConsumer.accept(new Session(flow.getTransport(), credential));
			listeners.forEach(Runnable::run);
		}
		catch (final IOException e) {
			EclipseUtils.showError(AUTHORIZATION_ERROR_MESSAGE, e);
		}
		finally {
			cancel();
		}
	}
	
	/**
	 * Functional method that aims to act as an {@link IJobFunction}.
	 * This function wait for code to be received and starts token
	 * request once it is done.
	 * 
	 * @param monitor Monitor to use for tracking login progress.
	 * @return {@link Status#OK_STATUS}
	 */
	private IStatus waitForCode(final IProgressMonitor monitor) {
		try {
			final String code = receiver.waitForCode();
			authorize(code);
		}
		catch (final IOException e) {
			EclipseUtils.showError(SERVER_WAIT_ERROR_MESSGAGE, e);
		}
		return Status.OK_STATUS;
	}
	
	/** Name used for the job task that wait for the code reception. **/
	private static final String JOB_NAME = "receive-code";
	
	/** {@inheritDoc} **/
	@Override
	public String getURL() throws IOException {
		this.redirectUri = receiver.getRedirectUri();
		final Job job = Job.create(JOB_NAME, this::waitForCode); 
		job.setSystem(true);
		job.setPriority(Job.SHORT);
		job.schedule();
		final AuthorizationCodeRequestUrl request = flow.newAuthorizationUrl();
		request.setRedirectUri(redirectUri);
		return request.build();
	}

	/**
	 * Creates and returns a valid {@link IGoogleLogger} instance.
	 * 
	 * @return Created instance.
	 * @throws GeneralSecurityException If any error occurs while creating the HTTP transport.
	 * @throws IOException If any error occurs while creating the HTTP transport, or reading the application secret.
	 */
	public static IGoogleLogger createLogger(final Consumer<Session> sessionConsumer) throws GeneralSecurityException, IOException {
		final NetHttpTransport transport = GoogleNetHttpTransport.newTrustedTransport();
		final Builder builder = new GoogleAuthorizationCodeFlow.Builder(transport, JSON_FACTORY, getSecret(), SCOPES);
		// TODO : Consider using secure storage for session.
		return new GoogleLogger(builder, sessionConsumer);
	}

	/**
	 * Static tool method that retrieves google client secret
	 * instance from internal JSON file.
	 * 
	 * @return {@link GoogleClientSecrets} instance created.
	 * @throws IOException If any error occurs while reading JSON file.
	 */
	private static GoogleClientSecrets getSecret() throws IOException {
		final InputStream stream = GoogleLogger.class.getResourceAsStream(SECRET_PATH);
		final InputStreamReader reader = new InputStreamReader(stream);
		return GoogleClientSecrets.load(JSON_FACTORY, reader);
	}

}
